Fix a bug and stop crimes
EyeYouReadyForIt/EyeYouReadyForIt pull request #32
Opened 2021-10-21 16:35 UTC by BoogieMonster1O1

Don't compare optionals with objects. And don't use fields ™

2021-11-02 04:49 UTC, heftymouse commented
wow just remembered this exists

2021-11-02 05:06 UTC, heftymouse commented
i don't really get the point of not having client as a field and passing csd to every command but is fine, the other changes are nice

2021-11-02 05:08 UTC, BoogieMonster1O1 commented
> i don't really get the point of not having client as a field and passing csd to every command but is fine, the other changes are nice

passing csd to every command so that their handlers don't have to get it themselves

2021-11-02 05:08 UTC, BoogieMonster1O1 commented
> i don't really get the point of not having client as a field and passing csd to every command but is fine, the other changes are nice

not having it as a field makes it more functional :tm:

2021-11-02 05:28 UTC, heftymouse commented
fair
fix stuff then it's ready to merge:tm:

2021-11-05 08:41 UTC, heftymouse requested changes
e

2021-11-05 09:43 UTC, BoogieMonster1O1 commented on app/src/main/java/io/github/boogiemonster1o1/eyeyoureadyforit/button/ButtonManager.java
> +				.flatMap((ButtonInteractionEvent event1) -> accept(event1, client))
it will but this is more comprehensive

2021-11-05 09:44 UTC, BoogieMonster1O1 commented on app/src/main/java/io/github/boogiemonster1o1/eyeyoureadyforit/App.java
> +				.onErrorContinue((t, o) -> {
what

2021-11-05 10:01 UTC, heftymouse commented on app/src/main/java/io/github/boogiemonster1o1/eyeyoureadyforit/button/ButtonManager.java
> +				.flatMap((ButtonInteractionEvent event1) -> accept(event1, client))
it's more comprehensive for absolutely no reason, it's completely impossible for it to be anything but a `ButtonInteractionEvent`

2021-11-05 10:04 UTC, heftymouse commented on app/src/main/java/io/github/boogiemonster1o1/eyeyoureadyforit/App.java
> +				.onErrorContinue((t, o) -> {
taken directly from reactor docs:
> Note that onErrorContinue() is a specialist operator that can make the behaviour of your reactive chain unclear. It operates on upstream, not downstream operators, it requires specific operator support to work, and the scope can easily propagate upstream into library code that didn't anticipate it (resulting in unintended behaviour.)

D4J has a better way to handle erroring elements in event fluxes which I shall describe shortly:tm:

2021-11-18 10:50 UTC, heftymouse commented
i don't even care any more i just want this to be done

2021-11-18 10:51 UTC, merged